# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc05d4c981e26e19a03c61430cd59729d5bb9e1f9157329c5cc9f89144eaceb263bb649b40ba382a797d81ea60824dbed529b4a3a6d0c68259894f5df88bbb95

test:
  secret_key_base: 4f89839a29e32e0055528c7b2e953785ceefbf82f000633c6e3c4c79d2a82edb2c40daa033edb2bd709a45aab55e4ad3fbaa7b2874ecf89a31e8be8c0e1355a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
